export const GET_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const FETCH_STORIES_REQUEST = 'FETCH_STORIES_REQUEST';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_FAILURE = 'FETCH_STORIES_FAILURE';

export const UPVOTE_CLICK = 'UPVOTE_CLICK';
export const UPVOTE_UPDATE = 'UPVOTE_UPDATE';
export const UPVOTE_UPDATE_SUCCESS = 'UPVOTE_UPDATE_SUCCESS';
export const NOMINATION_CLICK = 'NOMINATION_CLICK';

export const PUBLISH_STORY_REQUEST = 'PUBLISH_STORY_REQUEST';
export const PUBLISH_STORY_SUCCESS = 'PUBLISH_STORY_SUCCESS';
export const PUBLISH_STORY_FAILURE = 'PUBLISH_STORY_FAILURE';

export const CREATE_STORY_SHOW = 'CREATE_STORY_SHOW';
export const CREATE_STORY_HIDE = 'CREATE_STORY_HIDE';
